version: '3.3'

services:
######################################################
# MySQL SGBD  For Local Developement
######################################################
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'library_management'
      MYSQL_USER: 'library_admin'
      MYSQL_PASSWORD: 'library_admin_pass'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql-db:/var/lib/mysql
volumes:
  mysql-db: