version: '3.3'

services:
######################################################
# Database Services
######################################################

  # MySQL Service
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_DATABASE: 'library_management'
      MYSQL_USER: 'library_admin'
      MYSQL_PASSWORD: 'library_admin_pass'
      MYSQL_ROOT_PASSWORD: 'admin'
    ports:
      - '3306:3306'
    volumes:
      - mysql-db:/var/lib/mysql

  # Postgres that will hold the airflow metadata database
  airflow-metadata:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: 'airflow_user'
      POSTGRES_PASSWORD: 'airflow_pass'
      POSTGRES_DB: 'airflow_db'
    ports:
      - '5432:5432'
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "airflow_db", "-U", "airflow_user" ]
      timeout: 45s
      interval: 10s
      retries: 10

  # airflow_service 
  airflow: 
    build: ./docker/airflow
    restart: unless-stopped
    container_name: airflow
    volumes:
      - ./airflow/airflow.cfg:/opt/airflow/airflow.cfg
      - ./airflow/dags:/opt/airflow/dags
      # - ./extract-transform-load/extraction/mysql:/opt/airflow/dags/executables
    ports:
      - '8080:8080'
    healthcheck:
      test: ["CMD","nc","-z","airflow","8080"]
      timeout: 45s
      interval: 10s
      retries: 10

volumes:
  mysql-db: